default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: my_database_development

test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: my_database_prod
  username: railstest
  password: <%= ENV['RAILSTEST_DATABASE_PASSWORD'] %>
